<?php

declare(strict_types=1);

/**
 * This file is part of Laravel Harbor.
 *
 * (c) Mehran Rasulian <mehran.rasulian@gmail.com>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace App\Services\Comments;

class MarkdownBuilder
{
    public function prepareBody(array $rows): string
    {
        $body = [];

        foreach ($rows as $row) {
            $content = match ($row['type']) {
                'link' => sprintf('[%s](%s)', $row['content'], $row['content']),
                default => $row['content'],
            };

            $body[] = "| **{$row['name']}** | $content |";
        }

        return $this->getGitPrMarkdown($body);
    }

    private function getGitPrMarkdown(array $body): string
    {
        return "# PR Preview Environment Details
Hello! Here are the details of the preview environment for this pull request:

| Service     | Location                |
|-------------|-------------------------|\n"
            .implode("\n", $body).
            "\n \n You can access the website by clicking on the link above. The database details are provided for backend access and testing purposes. If you encounter any issues or have further questions, please don't hesitate to reach out! \n
---
*This comment was automatically generated by Laravel Harbor.*";
    }
}
