<?php

declare(strict_types=1);

/**
 * This file is part of Veyoze CLI.
 *
 * (c) Shvan Sheikha <shvansheikha@gmail.com>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace App\Services\Forge\Pipeline;

use App\Services\Forge\ForgeService;
use App\Traits\Outputifier;
use Closure;
use Illuminate\Support\Facades\Http;

class PutCommentOnPullRequest
{
    use Outputifier;

    public function __invoke(ForgeService $service, Closure $next)
    {
        if ($service->setting->gitCommentEnabled) {

            $this->information('Including the site information to the pull request.');

            $this->putCommentOnGithubPullRequest(
                $service->site->name,
                $service->setting->repository,
                $service->setting->gitIssueNumber,
                $service->setting->gitToken,
                $service->generateDatabaseName()
            );
        }

        return $next($service);
    }

    public function putCommentOnGithubPullRequest($siteName, $repository, $gitIssueNumber, $gitToken, $databaseName): void
    {
        $githubApi = sprintf(
            'https://api.github.com/repos/%s/issues/%s/comments',
            $repository,
            $gitIssueNumber
        );

        $body = ['body' => sprintf($this->getGitPrMarkdown(), $siteName, $siteName, $databaseName)];

        $header = [
            'Accept' => 'application/vnd.github+json',
            'Authorization' => "Bearer {$gitToken}",
            'X-GitHub-Api-Version' => '2022-11-28',
        ];

        Http::withHeaders($header)->post($githubApi, $body);
    }

    private function getGitPrMarkdown(): string
    {
        return "
            # PR Preview Environment Details

            Hello! Here are the details of the preview environment for this pull request:

            | Service     | Location                |
            |-------------|-------------------------|
            | **Website** | [%s](https://%s)        |
            | **Database**| %s                      |

            You can access the website by clicking on the link above.
            The database details are provided for backend access and testing purposes.
            If you encounter any issues or have further questions, please don't hesitate to reach out!

            ---
            *This comment was automatically generated by Veyoze.*
        ";
    }
}
