<?php

declare(strict_types=1);

/**
 * This file is part of Veyoze CLI.
 *
 * (c) Shvan Sheikha <shvansheikha@gmail.com>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace App\Services\Forge\Pipeline;

use App\Services\Forge\ForgeService;
use App\Services\Github\GithubService;
use App\Traits\Outputifier;
use Closure;

class PutCommentOnPullRequest
{
    use Outputifier;

    public function __construct(public GithubService $githubService)
    {
    }

    public function __invoke(ForgeService $service, Closure $next)
    {
        if ($service->setting->gitCommentEnabled || ! $service->siteNewlyMade) {

            $this->information('Including the site information to the pull request.');

            $dbUsername = $service->database['DB_DATABASE'] ?? '';
            $dbName = $service->database['DB_USERNAME'] ?? '';
            $dbPassword = $service->database['DB_PASSWORD'] ?? '';
            $dbHost = $service->server->ipAddress ?? "";
            $siteName = $service->site->name ?? '';

            $data = [
                [
                    'name' => 'Database Url',
                    'type' => 'text',
                    'content' => "mysql+ssh://forge@{$dbHost}/${dbUsername}:{$dbPassword}@127.0.0.1/${dbName}",
                ],
                [
                    'name' => 'Environment Url',
                    'type' => 'link',
                    'content' => $service->site?->isSecured ? 'https://' : 'http://' . $siteName,
                ]
            ];

            $this->githubService->putCommentOnGithubPullRequest($this->prepareBody($data));
        }

        return $next($service);
    }

    public function prepareBody(array $data): string
    {
        $body = [];

        foreach ($data as $datum) {
            $content = $datum['type'] === 'link' ? sprintf('[%s](%s)', $datum['name'], $datum['content']): $datum['content'];

            $body[] = "| **${datum['name']}** | $content |";
        }

        return $this->getGitPrMarkdown($body);
    }

    private function getGitPrMarkdown(array $body): string
    {
        return "# PR Preview Environment Details
Hello! Here are the details of the preview environment for this pull request:

| Service     | Location                |
|-------------|-------------------------|\n"
            . implode("\n", $body) .
"\n \n You can access the website by clicking on the link above. The database details are provided for backend access and testing purposes. If you encounter any issues or have further questions, please don't hesitate to reach out! \n
---
*This comment was automatically generated by Veyoze.*";
    }
}
